### PR TITLE
Naming convention and short_open_tag

### PR DESCRIPTION
**Pull request by donaldinou**
By default short_open_tag is off on every standard php5.x installation.
I know that since php 5.4.x the short tag <?= is still available even if short_open_tag is off. But I think that always write the long tag is a good practice.
We need to follow PSR coding standards

### CODE REVIEW

**Comment by mikeage** [comment]
I don't know if anyone is still monitoring this repo to merge changes, but you might find http://codex.galleryproject.org/Gallery3:FAQ#Why_do_you_use_PHP.27s_short_open_tags.3F to be of interest.

**Comment by donaldinou** [comment]
I'm agreed that the short tag "<?=" is accepted in the psr-1 standard. So, why not use it in template.
But the short tag "<?" should not be accepted in "*.php" files.
Because the short tag "<?=" is available without "short_open_tag" since php 5.4, we need to remove it in all template because it says that the requirements is php 5.2.x

Most of hosting services have "short_open_tag" set to "off". This is the reason of this pull request.
This project is in "hibernation" but I see that there still some pull request accepted.

**Comment by bharat** [comment]
Thanks for taking the time to do this work. Unfortunately, I disagree with the philosophical stance that we should use the <?php long form. I don't see that it adds value, and it comes at a clear cost in adding bytes to our template files. We are restrictive in the installer so that we can alert users if their environment doesn't have this flag off, but unless short_open_tags goes away entirely I don't see any value in going in this direction.

**Comment by donaldinou** [comment]
There is no problem for me. There is also interest for a "migration" to hhvm.
In my opinion it will be better to use a dedicated template. Most of frontend developer are familiar with it.
But it required more modification.
I closed this pull request.
Thanks for the reply.

**Comment by David-Guillot** [comment]
Hi everyone,

This is probably too late but for the record I strongly disagree with what's been decided here :
- PHP short tags are strongly recommended to be disabled because of the potential conflicts with XML opening tags (cf [here](http://php.net/manual/en/ini.core.php#ini.short-open-tag))
- Since PHP 5.4 (quite an old version of PHP, which [will be obsolete in September](https://secure.php.net/archive/2014.php#id2014-09-18-2), so we can hope most Gallery servers should be >=5.5), the short templating syntax (<?=) stays available even when short_open_tags is disabled ; so yes, this would mean migrating all Gallery templates from `<?` to `<?php` before all control structures, but it's actually pretty easy to do and unlike @bharat I don't see how "adding bytes to our template files" would hurt anyone, if it can help avoid problems and follow PHP best practices

Thanks

**Pull request closed without merging**
